return {
  diagnostics = {
    error = "●",
    warn = "●",
    hint = "●",
    info = "●",
  },
  directory = {
    folder_closed = "",
    folder_open = "",
    folder_empty = "",
    folder_empty_open = "",
    default = " ",
  },
  git = {
    added = "",
    modified = "",
    removed = "",
    renamed = "➜",
    untracked = "",
    ignored = "",
    unstaged = "U",
    staged = "",
    conflict = "",
    deleted = "",
  },
  gitsigns = {
    add = "┃",
    change = "┋",
    delete = "",
    topdelhfe = "",
    changedelete = "┃",
    untracked = "┃",
  },
  bbq_symbols = {
    modified = "●",
    ellipsis = "…",
    separator = "",
  },
  kinds = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "",
    Constant = "",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "",
    File = "",
    Folder = "",
    Function = "",
    Interface = "",
    Key = "",
    Keyword = "",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "",
    TypeParameter = "",
    Unit = "",
    Value = "",
    Variable = "",
    Macro = "", -- Macro
  },
  misc = {
    codeium = "󰘦 ",
  },
}
